#pragma once

#define LUL_EXCEPT_INTERNAL_NOT_IMPL 0x01
#define LUL_EXCEPT_INTERNAL_INIT_ERR 0x02

#define LUL_EXCEPT_INTERNAL_GLOBAL_SPACE_ACC_VIOL 0x20
#define LUL_EXCEPT_INTERNAL_GLOBAL_SPACE_NOT_INITIALIZED 0x21

#define LUL_EXCEPT_INTERNAL_LOG_ACCESS_VIOL 0x30

namespace LUL::Except
{
    LUL_DLL inline void Internal(const int32_t& exceptCode);
}